BEGIN

INSERT INTO raceGoals
VALUES(51, 'Chicago Triathlon', 'Chicago', 'Full Olympic', TO_DATE('2016-11-01', 'yyyy-mm-dd')); 

UPDATE raceGoals
SET RaceLocation= 'CHICAGO, ILLINOIS'
WHERE RaceLocation = 'Chicago';

DELETE FROM raceGoals
WHERE RaceDate > SYSDATE; 

--ROLLBACK; //YOU COULD INCLUDE THIS IF YOU WOULD LIKE TO ROLL BACK BEFORE ANY INSERTS
COMMIT WORK;
END;

--IT IS BENEFICIAL TO DO THIS IN ONE GO SINCE THEN EVERYTIME A NEW INSERT IS MADE WHERE THE RACE LOCATION IS CHICAGO, 
--IT IS THEN AUTOMATICALLY UPDATED TO THE STANDARD. ADDING THE DELETE ENSURES THAT NO EXCESS DATA IS TAKING UP SPACE, 
--IT IS HELPFUL TO DO THIS WITH EACH INSERT INTO RACEGOALS TO KEEP IT CONSTANTLY UPTODATE.
 